# License texts required when distributing the externally managed EasyTier binary.
# Stage them with scripts/stage-easytier-license.ps1; cached copies remain ignored.
[easytier_license]
version = "2.6.4"
file = "LICENSE"
url = "https://raw.githubusercontent.com/EasyTier/EasyTier/v2.6.4/LICENSE"
sha256 = "e3a994d82e644b03a792a930f574002658412f62407f5fee083f2555c5f23118"

[gnu_gpl]
version = "3.0"
file = "GPL-3.0.txt"
url = "https://www.gnu.org/licenses/gpl-3.0.txt"
sha256 = "3972dc9744f6499f0f9b2dbf76696f2ae7ad8af9b23dde66d6af86c9dfb36986"
